[project]
name = "hrms-attendex-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.122.0",
    "sqlalchemy>=2.0.44",
    "asyncpg>=0.29.0",
    "pydantic-settings>=2.0.0",
    "uvicorn>=0.38.0",
]
